### ISSUE TITLE
Evenements are not correctly displayed in Timeline View

### ISSUE THREAD

**Issue by trollepierre** [CroudSupport/vue-fullcalendar#109]
As seeing in pictures, the events are weirdly displayed on my timeline view.
https://github.com/trollepierre/vuefullcalendar-test-event-timeline/blob/master/src/App.vue

As I never succeed to display them correctly (it shows only the start time), I think there is a bug somewhere.

The option  rendering: 'background'  would fit my expectation, however I cannot the title on event...

Feel free to ask me for further investigation

<img width="786" alt="capture d ecran 2018-03-14 a 11 35 56" src="https://user-images.githubusercontent.com/8363334/37397463-f7dbca8e-277b-11e8-9e47-c000b1c9622e.png">

**Comment by BrockReece** [comment]
Thanks for this.
I'll have a quick look into this later.

If you get chance, can you replicate the issue in a codesandbox? It might be easier to iterate on the issue from there.

**Comment by trollepierre** [comment]
I am going to check what I can do. (this afternoon)

**Comment by BrockReece** [comment]
Thanks

**Comment by trollepierre** [comment]
I share your opinion. To me, the problem cannot come from your implementation.
However, their demo example looks like it's working:
https://fullcalendar.io/scheduler

**Comment by BrockReece** [comment]
Sure, I have a working example [here](https://codesandbox.io/s/qlp8jvko3j) too.

Does that help?

**Comment by Damanii** [comment]
When I remove the line:
`import "fullcalendar-scheduler";`
The date issue is fixed, but since that removes the import, timeline view doesn't work.

**Comment by BrockReece** [comment]
@Damanii, what do you mean by the issue is fixed?
When I looked into the this the other day these events showed fine in every view except the timeline views.

**Comment by BrockReece** [comment]
I have built this into a working sandbox
https://codesandbox.io/s/mz1xv83wn8

**Comment by Damanii** [comment]
@BrockReece Yeah, sorry I might have been unclear. So I've copied the code from the sandbox into my project, and it provided the following result:
<img width="725" alt="screen shot 2018-03-16 at 12 20 23 pm" src="https://user-images.githubusercontent.com/17342653/37532119-8020e2c8-2914-11e8-8435-036632e2a5c2.png">

I still get the undefined after the dates, which is removed when I deleted the line:
`import "fullcalendar-scheduler";`

For refrence:

```
"moment": "^2.20.1,"
"fullcalendar-scheduler": "^1.9.3",
"vue-full-calendar": "^2.5.2",
```

From my package.json, and:

```
import moment from 'moment'
import FullCalendar from "vue-full-calendar";
import "fullcalendar-scheduler";
import "fullcalendar/dist/fullcalendar.min.css";
import "fullcalendar-scheduler/dist/scheduler.min.css";
```

**Comment by Damanii** [comment]
So it turns out that in fullcalendar-scheduler there is another node_modules dir which has the fullcalendar. I deleted the file and it works fine now with all the features

**Comment by MrMitch** [comment]
I was having the same issue, as explained in https://github.com/fullcalendar/fullcalendar/issues/3911#issuecomment-458247701, I solved it by feeding the non-minified version of fullcalendar to webpack instead of the minified one.
